/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { webhook } from "./webhook";
import { slashCommandWebhook } from "./slashCommandWebhook";

export default {
  webhook,
  slashCommandWebhook,
};
