/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */

export interface SlashCommandWebhookValues {
  /**
   * Response Body
   *
   */
  responseBody?: string;
  /**
   * Content Type
   *
   * @default text\/plain
   */
  contentType?: string;
}

/**
 * Trigger for handling slash command and modal webhooks from Slack
 *
 * @description Trigger for handling slash command and modal webhooks from Slack
 */
export const slashCommandWebhook = {
  key: "slashCommandWebhook",
  perform: <TReturn>(_values: SlashCommandWebhookValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    responseBody: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    contentType: {
      inputType: "string",
      collection: undefined,
      default: `text\/plain`,
    },
  },
} as const;
