/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";

export interface WebhookValues {
  /**
   * Connection
   *
   */
  slackConnection: Connection;
}

/**
 * Receive and validate webhook requests from Slack&#39;s Events API for webhooks you configure.
 *
 * @description Receive and validate webhook requests from Slack's Events API for webhooks you configure.
 */
export const webhook = {
  key: "webhook",
  perform: <TReturn>(_values: WebhookValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    slackConnection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
} as const;
