/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { selectChannels } from "./selectChannels";
import { selectUsers } from "./selectUsers";

export default {
  selectChannels,
  selectUsers,
};
