/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral";

export interface Values {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Show channel ID in dropdown?
   *
   * @default false
   */
  showIdInDropdown?: boolean;
  /**
   * Include public channels?
   *
   * @default true
   */
  includePublicChannels?: boolean;
  /**
   * Include private channels?
   *
   * @default false
   */
  includePrivateChannels?: boolean;
  /**
   * Include multi-party IM (mpim) channels?
   *
   * @default false
   */
  includeMultiPartyImchannels?: boolean;
  /**
   * Include IM channels?
   *
   * @default false
   */
  includeImChannels?: boolean;
}

/**
 * Select Channel
 *
 * @description Select a Slack channel from a dropdown menu (up to 10,000 channels). To select Private Channels, you must access the API as a User and use the 'user_scope' configuration.
 */
export const selectChannels = {
  key: "selectChannels",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    showIdInDropdown: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    includePublicChannels: {
      inputType: "boolean",
      collection: undefined,
      default: `true`,
    },
    includePrivateChannels: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    includeMultiPartyImchannels: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    includeImChannels: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
  },
} as const;

/**
 * Select Channel DataSource Helper
 *
 * @comments Helper for direct usage in config wizard definitions.
 */
export const slackSelectChannels = (
  stableKey: string,
  values: {
    connection: ConfigVarExpression;
    showIdInDropdown?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
    includePublicChannels?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
    includePrivateChannels?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
    includeMultiPartyImchannels?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
    includeImChannels?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      component: "slack",
      key: "selectChannels",
      values,
    },
  });
};
