/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral";

export interface Values {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Show user ID in dropdown?
   *
   * @default false
   */
  showIdInDropdown?: boolean;
}

/**
 * Select User
 *
 * @description Select a User from a dropdown menu (up to 10,000 users)
 */
export const selectUsers = {
  key: "selectUsers",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    showIdInDropdown: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
  },
} as const;

/**
 * Select User DataSource Helper
 *
 * @comments Helper for direct usage in config wizard definitions.
 */
export const slackSelectUsers = (
  stableKey: string,
  values: {
    connection: ConfigVarExpression;
    showIdInDropdown?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      component: "slack",
      key: "selectUsers",
      values,
    },
  });
};
