/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { oauth2 } from "./oauth2";
import { webhookUrl } from "./webhookUrl";

export default {
  oauth2,
  webhookUrl,
};
