/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral";

export interface WebhookUrlValues {
  /**
   * Webhook URL
   *
   */
  webhookUrl: string;
}

/**
 * Slack Webhook URL
 *
 * @comments Authenticate requests to Slack using a Webhook URL.
 */
export const webhookUrl = {
  key: "webhookUrl",
  perform: (_values: WebhookUrlValues): Promise<void> => Promise.resolve(),
  inputs: {
    webhookUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * Slack Webhook URL Connection Helper
 *
 * @comments Helper for direct usage in config wizard definitions.
 */
export const slackWebhookUrl = (
  stableKey: string,
  values: {
    webhookUrl: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      component: "slack",
      key: "webhookUrl",
      values,
    },
  });
};
