/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ArchiveConversationValues {
  /**
   * Channel Name or ID
   *
   */
  channelName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Archive Conversation
 *
 * @description Archive an existing conversation
 */
export const archiveConversation = {
  key: "archiveConversation",
  perform: async <TReturn>(
    values: ArchiveConversationValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.archiveConversation({
      ...values,
    })) as TReturn;
  },
  inputs: {
    channelName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { ok: true } },
} as const;
