/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CloseConversationValues {
  /**
   * Conversation Name
   *
   */
  conversationName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Close Conversation
 *
 * @description Close an existing conversation
 */
export const closeConversation = {
  key: "closeConversation",
  perform: async <TReturn>(
    values: CloseConversationValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.closeConversation({
      ...values,
    })) as TReturn;
  },
  inputs: {
    conversationName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { ok: true, no_op: true, already_closed: true } },
} as const;
