/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ConversationExistsValues {
  /**
   * Channel Name or ID
   *
   */
  channelName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Conversation Exists
 *
 * @description Returns true if the conversation already exists
 */
export const conversationExists = {
  key: "conversationExists",
  perform: async <TReturn>(
    values: ConversationExistsValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.conversationExists({
      ...values,
    })) as TReturn;
  },
  inputs: {
    channelName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: true },
} as const;
