/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateConversationValues {
  /**
   * Conversation Name
   *
   */
  conversationName: string;
  /**
   * Is Private
   *
   * @default false
   */
  isPrivate?: boolean;
  /**
   * Team Id
   *
   */
  teamId?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Create Conversation
 *
 * @description Create a new conversation
 */
export const createConversation = {
  key: "createConversation",
  perform: async <TReturn>(
    values: CreateConversationValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.createConversation({
      ...values,
    })) as TReturn;
  },
  inputs: {
    conversationName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    isPrivate: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    teamId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      channels: [
        {
          id: "COZ7e3d",
          name: "example channel",
          is_im: false,
          created: 6426934241,
          creator: "example",
          purpose: {
            value: "This channel was created for an example response.",
          },
          is_group: false,
          unlinked: 0,
          is_channel: true,
          is_private: false,
          is_archived: false,
          name_normalized: "example channel",
          shared_team_ids: ["TW2oP78"],
        },
      ],
    },
  },
} as const;
