/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeletePendingMessageValues {
  /**
   * Message Id
   *
   */
  messageId: string;
  /**
   * Channel ID
   *
   */
  channelId: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Delete a pending scheduled message
 *
 * @description Delete the content and metadata of a pending scheduled message from a queue
 */
export const deletePendingMessage = {
  key: "deletePendingMessage",
  perform: async <TReturn>(
    values: DeletePendingMessageValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.deletePendingMessage({
      ...values,
    })) as TReturn;
  },
  inputs: {
    messageId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    channelId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { ok: true } },
} as const;
