/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteMessageValues {
  /**
   * Message Id
   *
   */
  messageId: string;
  /**
   * Channel ID
   *
   */
  channelId: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Delete message
 *
 * @description Delete the content and metadata of an existing message
 */
export const deleteMessage = {
  key: "deleteMessage",
  perform: async <TReturn>(values: DeleteMessageValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.deleteMessage({
      ...values,
    })) as TReturn;
  },
  inputs: {
    messageId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    channelId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { ok: true, ts: "1401383885.000061", channel: "C123ABC456" },
  },
} as const;
