/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListUsersConversationsValues {
  /**
   * User Id
   *
   */
  userId: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Limit
   *
   */
  limit?: string;
  /**
   * Cursor
   *
   */
  cursor?: string;
  /**
   * Team Id
   *
   */
  teamId?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Users Conversations
 *
 * @description List Users Conversations
 */
export const listUsersConversations = {
  key: "listUsersConversations",
  perform: async <TReturn>(
    values: ListUsersConversationsValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.listUsersConversations({
      ...values,
    })) as TReturn;
  },
  inputs: {
    userId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      channels: [
        {
          id: "COZ7e3d",
          name: "example channel",
          is_im: false,
          created: 6426934241,
          creator: "example",
          purpose: {
            value: "This channel was created for an example response.",
          },
          is_group: false,
          unlinked: 0,
          is_channel: true,
          is_private: false,
          is_archived: false,
          name_normalized: "example channel",
          shared_team_ids: ["TW2oP78"],
        },
      ],
    },
  },
} as const;
