/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListConversationMembersValues {
  /**
   * Channel Name or ID
   *
   */
  channelName: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Limit
   *
   */
  limit?: string;
  /**
   * Cursor
   *
   */
  cursor?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Conversation Members
 *
 * @description List all members of a conversation
 */
export const listConversationMembers = {
  key: "listConversationMembers",
  perform: async <TReturn>(
    values: ListConversationMembersValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.listConversationMembers({
      ...values,
    })) as TReturn;
  },
  inputs: {
    channelName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      members: ["U023BECGF", "U061F7AUR", "W012A3CDE"],
      response_metadata: { next_cursor: "e3VzZXJfaWQ6IFcxMjM0NTY3fQ==" },
    },
  },
} as const;
