/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListFilesValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Cursor
   *
   */
  cursor?: string;
}

/**
 * List Files
 *
 * @description List all available files
 */
export const listFiles = {
  key: "listFiles",
  perform: async <TReturn>(values: ListFilesValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.listFiles({ ...values })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      files: [
        {
          id: "F0S43P1CZ",
          ims: [],
          mode: "hosted",
          name: "billair.gif",
          size: 144538,
          user: "U061F7AUR",
          pjpeg: "https://.../billair_pjpeg.jpg",
          title: "billair.gif",
          groups: [],
          created: 1531763254,
          channels: ["C0T8SE4AU"],
          editable: false,
          filetype: "gif",
          mimetype: "image/gif",
          thumb_64: "https://.../billair_64.png",
          thumb_80: "https://.../billair_80.png",
          username: "",
          is_public: true,
          permalink: "https://.../billair.gif",
          thumb_160: "https://.../billair_=_160.png",
          thumb_360: "https://.../billair_360.png",
          timestamp: 1531763254,
          original_h: 226,
          original_w: 176,
          is_external: false,
          pretty_type: "GIF",
          thumb_360_h: 226,
          thumb_360_w: 176,
          url_private: "https://.../billair.gif",
          deanimate_gif: "https://.../billair_deanimate_gif.png",
          external_type: "",
          thumb_360_gif: "https://.../billair_360.gif",
          comments_count: 0,
          display_as_bot: false,
          permalink_public: "https://.../...",
          public_url_shared: false,
          image_exif_rotation: 1,
          url_private_download: "https://.../billair.gif",
        },
        {
          id: "F0S43P1CZ",
          ims: [],
          mode: "hosted",
          name: "billair.gif",
          size: 144538,
          user: "U061F7AUR",
          pjpeg: "https://.../billair_pjpeg.jpg",
          title: "billair.gif",
          groups: [],
          created: 1531763254,
          channels: ["C0T8SE4AU"],
          editable: false,
          filetype: "gif",
          mimetype: "image/gif",
          thumb_64: "https://.../billair_64.png",
          thumb_80: "https://.../billair_80.png",
          username: "",
          is_public: true,
          permalink: "https://.../billair.gif",
          thumb_160: "https://.../billair_=_160.png",
          thumb_360: "https://.../billair_360.png",
          timestamp: 1531763254,
          original_h: 226,
          original_w: 176,
          is_external: false,
          pretty_type: "GIF",
          thumb_360_h: 226,
          thumb_360_w: 176,
          url_private: "https://.../billair.gif",
          deanimate_gif: "https://.../billair_deanimate_gif.png",
          external_type: "",
          thumb_360_gif: "https://.../billair_360.gif",
          comments_count: 0,
          display_as_bot: false,
          permalink_public: "https://.../...",
          public_url_shared: false,
          image_exif_rotation: 1,
          url_private_download: "https://.../billair.gif",
        },
      ],
      paging: { page: 1, count: 100, pages: 1, total: 2 },
    },
  },
} as const;
