/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListScheduledMessagesValues {
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Scheduled Messages
 *
 * @description List all scheduled messages
 */
export const listScheduledMessages = {
  key: "listScheduledMessages",
  perform: async <TReturn>(
    values: ListScheduledMessagesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.listScheduledMessages({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      response_metadata: { next_cursor: "" },
      scheduled_messages: [
        {
          id: 1298393284,
          text: "Here's a message for you in the future",
          post_at: 1551991428,
          channel_id: "C1H9RESGL",
          date_created: 1551891734,
        },
      ],
    },
  },
} as const;
