/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface OpenViewValues {
  /**
   * View
   *
   * @default {\\n  \\"type\\": \\"modal\\",\\n  \\"title\\": {\\n    \\"type\\": \\"plain_text\\",\\n    \\"text\\": \\"Modal title\\"\\n  },\\n  \\"blocks\\": [\\n    {\\n      \\"type\\": \\"section\\",\\n      \\"text\\": {\\n        \\"type\\": \\"mrkdwn\\",\\n        \\"text\\": \\"It's Block Kit...but _in a modal_\\"\\n      },\\n      \\"block_id\\": \\"section1\\",\\n      \\"accessory\\": {\\n        \\"type\\": \\"button\\",\\n        \\"text\\": {\\n          \\"type\\": \\"plain_text\\",\\n          \\"text\\": \\"Click me\\"\\n        },\\n        \\"action_id\\": \\"button_abc\\",\\n        \\"value\\": \\"Button value\\",\\n        \\"style\\": \\"danger\\"\\n      }\\n    },\\n    {\\n      \\"type\\": \\"input\\",\\n      \\"label\\": {\\n        \\"type\\": \\"plain_text\\",\\n        \\"text\\": \\"Input label\\"\\n      },\\n      \\"element\\": {\\n        \\"type\\": \\"plain_text_input\\",\\n        \\"action_id\\": \\"input1\\",\\n        \\"placeholder\\": {\\n          \\"type\\": \\"plain_text\\",\\n          \\"text\\": \\"Type in here\\"\\n        },\\n        \\"multiline\\": false\\n      },\\n      \\"optional\\": false\\n    }\\n  ],\\n  \\"close\\": {\\n    \\"type\\": \\"plain_text\\",\\n    \\"text\\": \\"Cancel\\"\\n  },\\n  \\"submit\\": {\\n    \\"type\\": \\"plain_text\\",\\n    \\"text\\": \\"Save\\"\\n  },\\n  \\"private_metadata\\": \\"Shhhhhhhh\\",\\n  \\"callback_id\\": \\"view_identifier_12\\"\\n}
   */
  view?: string;
  /**
   * Trigger ID
   *
   */
  trigger_id: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Open Views
 *
 * @description Open a view for a user.
 */
export const openView = {
  key: "openView",
  perform: async <TReturn>(values: OpenViewValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.openView({ ...values })) as TReturn;
  },
  inputs: {
    view: {
      inputType: "code",
      collection: undefined,
      default: `{
  "type": "modal",
  "title": {
    "type": "plain_text",
    "text": "Modal title"
  },
  "blocks": [
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "It's Block Kit...but _in a modal_"
      },
      "block_id": "section1",
      "accessory": {
        "type": "button",
        "text": {
          "type": "plain_text",
          "text": "Click me"
        },
        "action_id": "button_abc",
        "value": "Button value",
        "style": "danger"
      }
    },
    {
      "type": "input",
      "label": {
        "type": "plain_text",
        "text": "Input label"
      },
      "element": {
        "type": "plain_text_input",
        "action_id": "input1",
        "placeholder": {
          "type": "plain_text",
          "text": "Type in here"
        },
        "multiline": false
      },
      "optional": false
    }
  ],
  "close": {
    "type": "plain_text",
    "text": "Cancel"
  },
  "submit": {
    "type": "plain_text",
    "text": "Save"
  },
  "private_metadata": "Shhhhhhhh",
  "callback_id": "view_identifier_12"
}`,
    },
    trigger_id: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      view: {
        id: "VMHU10V25",
        hash: "156772938.1827394",
        type: "modal",
        state: { values: {} },
        title: { text: "Quite a plain modal", type: "plain_text" },
        app_id: "AA4928AQ",
        blocks: [
          {
            type: "input",
            label: { text: "A simple label", type: "plain_text", emoji: true },
            element: { type: "plain_text_input", action_id: "an_action_id" },
            block_id: "a_block_id",
            optional: false,
          },
        ],
        bot_id: "BA13894H",
        submit: { text: "Create", type: "plain_text" },
        team_id: "T8N4K1JN",
        callback_id: "identify_your_modals",
        external_id: "",
        root_view_id: "VMHU10V25",
        clear_on_close: false,
        notify_on_close: false,
        private_metadata: "Shh it is a secret",
      },
    },
  },
} as const;
