/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface PostBlockMessageValues {
  /**
   * Blocks
   *
   * @default {\\n  \\"blocks\\": [\\n    {\\n      \\"type\\": \\"section\\",\\n      \\"text\\": {\\n        \\"type\\": \\"plain_text\\",\\n        \\"text\\": \\"Hello world\\"\\n      }\\n    }\\n  ]\\n}
   */
  blocks?: string;
  /**
   * Alt Message
   *
   */
  message: string;
  /**
   * Channel Name or ID
   *
   */
  channelName: string;
  /**
   * Bot Username
   *
   */
  username?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Message Id
   *
   */
  messageId?: string;
}

/**
 * Post Block Message
 *
 * @description Post a message to a slack channel
 */
export const postBlockMessage = {
  key: "postBlockMessage",
  perform: async <TReturn>(
    values: PostBlockMessageValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.postBlockMessage({
      ...values,
    })) as TReturn;
  },
  inputs: {
    blocks: {
      inputType: "code",
      collection: undefined,
      default: `{
  "blocks": [
    {
      "type": "section",
      "text": {
        "type": "plain_text",
        "text": "Hello world"
      }
    }
  ]
}`,
    },
    message: {
      inputType: "text",
      collection: undefined,
      default: ``,
      required: true,
    },
    channelName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    username: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    messageId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      ts: "1646951430.367539",
      channel: "C011B7U3R9U",
      message: {
        ts: "1646951430.367539",
        text: "The message I sent",
        type: "message",
        bot_id: "B036D2DCT54",
        subtype: "bot_message",
        username: "My Slack App",
      },
      response_metadata: {
        scopes: [
          "identify",
          "chat:write",
          "chat:write.public",
          "chat:write.customize",
        ],
        acceptedScopes: ["chat:write"],
      },
    },
  },
} as const;
