/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface RenameConversationValues {
  /**
   * Conversation Name
   *
   */
  conversationName: string;
  /**
   * New Conversation Name
   *
   */
  newConversationName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Rename Conversation
 *
 * @description Rename an existing conversation
 */
export const renameConversation = {
  key: "renameConversation",
  perform: async <TReturn>(
    values: RenameConversationValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.renameConversation({
      ...values,
    })) as TReturn;
  },
  inputs: {
    conversationName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    newConversationName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      channel: {
        id: "C012AB3CD",
        name: "general",
        is_im: false,
        topic: {
          value: "For public discussion of generalities",
          creator: "W012A3BCD",
          last_set: 1449709364,
        },
        locale: "en-US",
        created: 1449252889,
        creator: "W012A3BCD",
        is_mpim: false,
        purpose: {
          value: "This part of the workspace is for fun. Make fun here.",
          creator: "W012A3BCD",
          last_set: 1449709364,
        },
        is_group: false,
        unlinked: 0,
        is_member: true,
        is_shared: false,
        last_read: "1502126650.228446",
        is_channel: true,
        is_general: true,
        is_private: false,
        is_archived: false,
        num_members: 23,
        is_read_only: false,
        is_ext_shared: false,
        is_org_shared: false,
        pending_shared: [],
        previous_names: ["specifics", "abstractions", "etc"],
        name_normalized: "general",
        is_pending_ext_shared: false,
      },
    },
  },
} as const;
