/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface SearchAllValues {
  /**
   * Query
   *
   */
  query: string;
  /**
   * Count
   *
   */
  count?: string;
  /**
   * Sort
   *
   * @default score
   */
  sort?: string;
  /**
   * Sort Direction
   *
   * @default desc
   */
  sort_dir?: string;
  /**
   * Page
   *
   * @default 1
   */
  page?: string;
  /**
   * Highlight
   *
   * @default false
   */
  highlight?: boolean;
  /**
   * Team Id
   *
   */
  team_id?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Search All
 *
 * @description Searches for messages and files matching a query.
 */
export const searchAll = {
  key: "searchAll",
  perform: async <TReturn>(values: SearchAllValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.searchAll({ ...values })) as TReturn;
  },
  inputs: {
    query: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    count: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    sort: {
      inputType: "string",
      collection: undefined,
      default: `score`,
    },
    sort_dir: {
      inputType: "string",
      collection: undefined,
      default: `desc`,
    },
    page: {
      inputType: "string",
      collection: undefined,
      default: `1`,
    },
    highlight: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    team_id: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      files: {
        total: 1,
        paging: { page: 1, count: 20, pages: 1, total: 1 },
        matches: [
          {
            id: "F7PKF1NR7",
            ims: [],
            mode: "hosted",
            name: "slack workflow diagram.png",
            size: 35705,
            user: "U2U85N1RZ",
            score: "0.99982661240974",
            title: "slack workflow diagram",
            groups: [],
            created: 1508804330,
            preview: null,
            channels: [],
            editable: false,
            filetype: "png",
            mimetype: "image/png",
            thumb_64:
              "https://files.slack.com/files-tmb/T2U81E2FZ-F7PKF1NR7-19f33fc256/slack_workflow_diagram_64.png",
            thumb_80:
              "https://files.slack.com/files-tmb/T2U81E2FZ-F7PKF1NR7-19f33fc256/slack_workflow_diagram_80.png",
            top_file: false,
            username: "amy",
            is_public: true,
            permalink:
              "https://example.slack.com/files/U2U85N1RZ/F7PKF1NR7/slack_workflow_diagram.png",
            thumb_160:
              "https://files.slack.com/files-tmb/T2U81E2FZ-F7PKF1NR7-19f33fc256/slack_workflow_diagram_160.png",
            thumb_360:
              "https://files.slack.com/files-tmb/T2U81E2FZ-F7PKF1NR7-19f33fc256/slack_workflow_diagram_360.png",
            timestamp: 1508804330,
            original_h: 117,
            original_w: 128,
            is_external: false,
            pretty_type: "PNG",
            thumb_360_h: 117,
            thumb_360_w: 128,
            url_private:
              "https://files.slack.com/files-pri/T2U81E2FZ-F7PKF1NR7/slack_workflow_diagram.png",
            external_type: "",
            comments_count: 1,
            display_as_bot: false,
            initial_comment: {
              id: "Fc7NLL52E7",
              user: "U2U85N1RZ",
              comment: "Sure! Here's the workflow diagram!",
              created: 1508804330,
              is_intro: true,
              timestamp: 1508804330,
            },
            permalink_public:
              "https://slack-files.com/T2U81E2FZ-F7PKF1NR7-bea9143f18",
            public_url_shared: false,
            image_exif_rotation: 1,
            url_private_download:
              "https://files.slack.com/files-pri/T2U81E2FZ-F7PKF1NR7/download/slack_workflow_diagram.png",
          },
        ],
        pagination: {
          last: 1,
          page: 1,
          first: 1,
          per_page: 20,
          page_count: 1,
          total_count: 1,
        },
      },
      posts: { total: 0, matches: [] },
      query: "diagram",
      messages: {
        total: 1,
        paging: { page: 1, count: 20, pages: 1, total: 1 },
        matches: [
          {
            ts: "1508804330.000296",
            iid: "35692677-e60e-43d9-ac45-1987cea88975",
            next: {
              ts: "1508804378.000219",
              iid: "6f510ea1-e1d3-4f3f-bdb9-f9c6f6e9d609",
              text: "Thanks!",
              type: "message",
              user: "U2U85HJ7R",
              username: "john",
            },
            team: "T2U81E2FZ",
            text: "uploaded a file: <https://example.slack.com/files/U2U85N1RZ/F7PKF1NR7/slack_workflow_diagram.png|slack workflow diagram> and commented: Sure! Here's the workflow diagram!",
            type: "message",
            user: "U2U85N1RZ",
            channel: {
              id: "C2U86NC6M",
              name: "general",
              is_mpim: false,
              is_shared: false,
              is_private: false,
              is_ext_shared: false,
              is_org_shared: false,
              pending_shared: [],
              is_pending_ext_shared: false,
            },
            previous: {
              ts: "1508804301.000026",
              iid: "aba8603c-0543-4fb2-9118-a5ac85f3d138",
              text: "Can you send me the Slack workflow diagram?",
              type: "message",
              user: "U2U85HJ7R",
              username: "john",
            },
            username: "amy",
            permalink:
              "https://example.slack.com/archives/C2U86NC6M/p1508804330000296",
          },
        ],
        pagination: {
          last: 1,
          page: 1,
          first: 1,
          per_page: 20,
          page_count: 1,
          total_count: 1,
        },
      },
    },
  },
} as const;
