/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface SearchFilesValues {
  /**
   * Query
   *
   */
  query: string;
  /**
   * Count
   *
   */
  count?: string;
  /**
   * Highlight
   *
   * @default false
   */
  highlight?: boolean;
  /**
   * Page
   *
   * @default 1
   */
  page?: string;
  /**
   * Sort
   *
   * @default score
   */
  sort?: string;
  /**
   * Sort Direction
   *
   * @default desc
   */
  sort_dir?: string;
  /**
   * Team Id
   *
   */
  team_id?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Search Files
 *
 * @description Searches for files matching a query.
 */
export const searchFiles = {
  key: "searchFiles",
  perform: async <TReturn>(values: SearchFilesValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.searchFiles({
      ...values,
    })) as TReturn;
  },
  inputs: {
    query: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    count: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    highlight: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    page: {
      inputType: "string",
      collection: undefined,
      default: `1`,
    },
    sort: {
      inputType: "string",
      collection: undefined,
      default: `score`,
    },
    sort_dir: {
      inputType: "string",
      collection: undefined,
      default: `desc`,
    },
    team_id: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      ok: true,
      files: {
        total: 3,
        paging: { page: 1, count: 20, pages: 1, total: 3 },
        matches: [
          {
            id: "F7H0D7ZBB",
            ims: [],
            mode: "hosted",
            name: "computer.gif",
            size: 1639034,
            user: "U2U85N1RZ",
            score: "0.38899223746309",
            title: "computer.gif",
            groups: [],
            created: 1507850315,
            preview: null,
            channels: [],
            editable: false,
            filetype: "gif",
            mimetype: "image/gif",
            thumb_64:
              "https://files.slack.com/files-tmb/T2U81E2BB-F7H0D7ZBB-21624821e6/computer_64.png",
            thumb_80:
              "https://files.slack.com/files-tmb/T2U81E2BB-F7H0D7ZBB-21624821e6/computer_80.png",
            top_file: false,
            username: "",
            is_public: true,
            permalink:
              "https://eventsdemo.slack.com/files/U2U85N1RZ/F7H0D7ZBB/computer.gif",
            reactions: [
              {
                name: "stuck_out_tongue_winking_eye",
                count: 1,
                users: ["U2U85N1RZ"],
              },
            ],
            thumb_160:
              "https://files.slack.com/files-tmb/T2U81E2BB-F7H0D7ZBB-21624821e6/computer_160.png",
            thumb_360:
              "https://files.slack.com/files-tmb/T2U81E2BB-F7H0D7ZBB-21624821e6/computer_360.png",
            thumb_480:
              "https://files.slack.com/files-tmb/T2U81E2BB-F7H0D7ZBB-21624821e6/computer_480.png",
            timestamp: 1507850315,
            original_h: 313,
            original_w: 500,
            is_external: false,
            pretty_type: "GIF",
            thumb_360_h: 225,
            thumb_360_w: 360,
            thumb_480_h: 300,
            thumb_480_w: 480,
            url_private:
              "https://files.slack.com/files-pri/T2U81E2BB-F7H0D7ZBB/computer.gif",
            deanimate_gif:
              "https://files.slack.com/files-tmb/T2U81E2BB-F7H0D7ZBB-21624821e6/computer_deanimate_gif.png",
            external_type: "",
            thumb_360_gif:
              "https://files.slack.com/files-tmb/T2U81E2BB-F7H0D7ZBB-21624821e6/computer_360.gif",
            thumb_480_gif:
              "https://files.slack.com/files-tmb/T2U81E2BB-F7H0D7ZBB-21624821e6/computer_480.gif",
            comments_count: 1,
            display_as_bot: false,
            permalink_public:
              "https://slack-files.com/T2U81E2BB-F7H0D7ZBB-85b7f5557e",
            public_url_shared: false,
            image_exif_rotation: 1,
            url_private_download:
              "https://files.slack.com/files-pri/T2U81E2BB-F7H0D7ZBB/download/computer.gif",
          },
        ],
        pagination: {
          last: 3,
          page: 1,
          first: 1,
          per_page: 20,
          page_count: 1,
          total_count: 3,
        },
      },
      query: "computer.gif",
    },
  },
} as const;
