/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface SetConversationPurposeValues {
  /**
   * Channel Name or ID
   *
   */
  channelName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Conversation Purpose
   *
   */
  purpose: string;
}

/**
 * Set Conversation Purpose
 *
 * @description Set the purpose of an existing conversation
 */
export const setConversationPurpose = {
  key: "setConversationPurpose",
  perform: async <TReturn>(
    values: SetConversationPurposeValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.slack.setConversationPurpose({
      ...values,
    })) as TReturn;
  },
  inputs: {
    channelName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    purpose: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: { data: { ok: true } },
} as const;
