/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import actions from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export { actions, connections, dataSources, triggers };

export default {
  key: "slack",
  public: true,
  signature: "5dee5a86c1c31fa283a6d14ccea1eec84a985c0d",
  actions,
  dataSources,
  connections,
  triggers,
} as const;
