import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen">
          {/* Sidebar */}
          <div className="w-64 bg-zinc-900 border-r border-zinc-800 p-6">
            <div className="mb-8">
              <h1 className="text-xl font-bold text-zinc-100">Acme SaaS</h1>
            </div>
            
            <nav className="space-y-2">
              <Link 
                href="/" 
                className="block px-4 py-2 text-zinc-300 hover:bg-zinc-800 hover:text-zinc-100 rounded-md transition-colors"
              >
                Home
              </Link>
              <Link 
                href="/integration-marketplace" 
                className="block px-4 py-2 text-zinc-300 hover:bg-zinc-800 hover:text-zinc-100 rounded-md transition-colors"
              >
                Integration Marketplace
              </Link>
              <Link 
                href="/ai-chat" 
                className="block px-4 py-2 text-zinc-300 hover:bg-zinc-800 hover:text-zinc-100 rounded-md transition-colors"
              >
                AI Chat
              </Link>
            </nav>
          </div>
          
          {/* Main content */}
          <div className="flex-1 overflow-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
